#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format
npx lint-staged

echo "
             _ _     _            _       
 _   _ _ __ (_) |_  | |_ ___  ___| |_ ___ 
| | | | '_ \| | __| | __/ _ \/ __| __/ __|
| |_| | | | | | |_  | ||  __/\__ \ |_\__ \ 
 \__,_|_| |_|_|\__|  \__\___||___/\__|___/                                          
"
npm run test
